hackaton/urls.py
from django.urls import path
from . import views

app_name = 'hackaton'

urlpatterns = [
    path("", views.index, name="index"),
    path("registration/", views.registration, name="registration"),
    path("partners/", views.partners, name="partners"),
    path("info/", views.info, name="info"),
    path("polozhenie_nordhack/", views.open_pdf, name="polozhenie_nordhack"),
    path("day1/", views.open_pdf, name="day1"),
    path("day2/", views.open_pdf, name="day2"),
    path("day3/", views.open_pdf, name="day3"),
]

hackatonSite/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('nordhack/', include('hackaton.urls')),
    path('nordhack/users/', include('users.urls')),
    path('nordhack/admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.profile, name='profile'),
    path("login", views.login_view, name='login'),
    path("logout", views.logout_view, name='logout'),
    path("addCommand", views.add_command, name='add_command'),
    path("delCommand", views.del_command, name='del_command'),
    path("addMember", views.add_member, name='add_member'),
    path("delMember", views.del_member, name='del_member'),
    path("register", views.register, name='registration'),
    path("update_user_info", views.update_user_info, name='update_user_info'),
    path("deleteUser", views.delete_user, name='delete_user'),
    path("command", views.command, name='command'),
    path("schedule", views.schedule, name='schedule'),
    path("task", views.task, name='task'),
    path("newTask", views.new_task, name='new_task'),
    path("changeTask", views.change_task, name='change_task'),
    path("newHackathon", views.new_hackathon, name='new_hackathon'),
    path("updateDateHackathon", views.update_date_hackathon, name='update_date_hackathon'),
    path("add_representative", views.add_representative, name='add_representative'),
    path("add_org", views.add_org, name='add_org'),
    path("add_task", views.add_task, name='add_task'),
]

hackaton/models.py
from django.db import models

# Create your models here.

hackaton/views.py
from django.shortcuts import render
from django.http import FileResponse, HttpResponse
from os import path
from django.conf import settings
from users.models import Hackathons, ParticipatingOrganizations
import pymorphy3
from django.utils.translation import gettext as _

morph = pymorphy3.MorphAnalyzer()
# Create your views here.
def index(request):
    hackaton = Hackathons.objects.all()[0]

    start = hackaton.start_date
    start_month = _(start.strftime("%B"))
    start_parsed_month = morph.parse(start_month)[0]
    start_month_name = start_parsed_month.inflect({'gent'}).word

    end = hackaton.end_date
    end_month = _(end.strftime("%B"))
    end_parsed_month = morph.parse(end_month)[0]
    end_month_name = end_parsed_month.inflect({'gent'}).word

    return render(request, 'hackaton/index.html', {
        'hackaton': hackaton.name,
        'start': start.strftime("%d ") + start_month_name,
        'end': end.strftime("%d ") + end_month_name,
        'date': start,
    })

def partners(request):
    return render(request, 'hackaton/partners.html', {
        'orgs':ParticipatingOrganizations.objects.all(),
    })

def open_pdf(request):

    return render(request, 'hackaton/polozhenie.html', {
        'file':f'hackaton/{request.resolver_match.url_name}.pdf'
    })

def info(request):
    return render(request, 'hackaton/info.html')
def registration(request):
    return render(request, 'hackaton/registration.html', {
        'registration':True,
    })

hackaton/templates/hackaton/index.html
{% extends 'hackaton/layout.html' %}
{% load static %}
{% block main %}


<!-- Start Hero Area -->
<section class="hero-area">
    <div class="main__circle"></div>
    <div class="main__circle2"></div>
    <div class="main__circle3"></div>
    <div class="main__circle4"></div>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 offset-lg-3 col-md-12 col-12">
                <div class="hero-content">
                    <h5 class="wow zoomIn" data-wow-delay=".2s">
                        <i class="lni lni-map-marker"></i><a href="https://yandex.ru/maps/-/CCUWu0BKLC">МАГУ,
                        Мурманск</a>
                    </h5>
                    <h2 class="wow fadeInUp" data-wow-delay=".4s">{{hackaton}}</h2>
                    <p class="wow fadeInUp" data-wow-delay=".6s">
                        Кафедра математики, физики и информационных технологий приглашает всех желающих принять участие в региональном состязательном мероприятии
                        «{{hackaton}}», который будет проходить на базе факультета математических и естественных наук
                        ФГБОУ ВО «МАГУ» с {{start}} по {{end}}.
                    </p>
                    <div class="button wow fadeInUp" data-wow-delay=".8s">
                        <a href="{% url 'users:registration' %}" class="btn ">Зарегистрироваться</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Hero Area -->

<!-- Start Count Down Area -->
<div class="count-down">

    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="box-head">
                    <div class="box-content">
                        <div class="box">
                            <h1 id="days">000</h1>
                            <h2 id="daystxt">Дней</h2>
                        </div>
                        <div class="box">
                            <h1 id="hours">00</h1>
                            <h2 id="hourstxt">Часов</h2>
                        </div>
                        <div class="box">
                            <h1 id="minutes">00</h1>
                            <h2 id="minutestxt">Минуты</h2>
                        </div>
                        <div class="box">
                            <h1 id="seconds">00</h1>
                            <h2 id="secondstxt">Секунды</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Count Down Area -->

<div class="main-content text-dark">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 wow fadeInUp" data-wow-delay=".2s">

                <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg'%}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                    <h3>КОГО МЫ ЖДЕМ</h3>
                    <p>
                        Обучающиеся школ города и области (класс и профиль не имеют значения) и студентов колледжей и вузов, простых IT-шников от компаний. Команда состоит из 3-4 человек.
                        Можно собрать команду заранее, можно влиться в команду на месте.
                    </p>
                </div>

                <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                    <h3>КОГДА ЭТО БУДЕТ</h3>
                    <p>
                        С {{start}} по {{end}} — Несколько дней душевного кодинга и решения практических задач с полным погружением в проблему.
                    </p>
                </div>

                <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                    <h3>ПРО ЧТО ЭТО БУДЕТ</h3>
                    <p>
                        Самые актуальные во все времена направления — умный город, большие данные, информационная безопасность, разработка компьютерной игры и визуализация данных (на выбор).
                    </p>
                </div>

                <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                    <h3>ЧЕМ МОЖНО ПОЛЬЗОВАТЬСЯ</h3>
                    <p>
                        Всем, что сможете принести — свой ноутбук, свой мобильный интернет, книги и прочие полезные полезности.
                    </p>
                </div>

                <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                    <h3>ГДЕ ЭТО БУДЕТ</h3>
                    <p>
                        Площадка Мурманского арктического государственного университета.
                    </p>
                </div>
            </div>

            <div class="col-lg-1">
            </div>

            <div class="col">
                <div class="main-img"><img class="center-pic" src="{% static 'hackaton/images/main.jpg' %}" alt="img"></div>
                <div class="main-img"><img class="center-pic" src="{% static 'hackaton/images/main1.jpg' %}" alt="img"></div>
                <div class="main-img"><img class="center-pic" src="{% static 'hackaton/images/main2.jpg' %}" alt="img"></div>
            </div>
        </div>
    </div>

</div>

<script>
            const finaleDate = new Date("{{date|date:'Y-m-d'}}").getTime();

            const timer = () => {
                const now = new Date().getTime();
                let diff = finaleDate - now;
                if (diff < 0) {
                    document.querySelector('.alert').style.display = 'block';
                    document.querySelector('.container').style.display = 'none';
                }

                let days = Math.floor(diff / (1000 * 60 * 60 * 24));
                let hours = Math.floor(diff % (1000 * 60 * 60 * 24) / (1000 * 60 * 60));
                let minutes = Math.floor(diff % (1000 * 60 * 60) / (1000 * 60));
                let seconds = Math.floor(diff % (1000 * 60) / 1000);

                days <= 99 ? days = `0${days}` : days;
                days <= 9 ? days = `00${days}` : days;
                hours <= 9 ? hours = `0${hours}` : hours;
                minutes <= 9 ? minutes = `0${minutes}` : minutes;
                seconds <= 9 ? seconds = `0${seconds}` : seconds;

                document.querySelector('#days').textContent = days;
                document.querySelector('#hours').textContent = hours;
                document.querySelector('#minutes').textContent = minutes;
                document.querySelector('#seconds').textContent = seconds;

                if(days%10 === 0 || days%10 > 4 || Math.floor(days/10) === 1 || (days%100 > 10 && days%100 < 20)){
                    document.querySelector('#daystxt').textContent = 'Дней';
                }
                else if(days%10 === 1){
                    document.querySelector('#daystxt').textContent = 'День';
                }
                else if(days%10 > 1 && days%10 < 5){
                    document.querySelector('#daystxt').textContent = 'Дня';
                }

                if(hours%10 === 0 || hours%10 > 4 || Math.floor(hours/10) === 1){
                    document.querySelector('#hourstxt').textContent = 'Часов';
                }
                else if(hours%10 === 1){
                    document.querySelector('#hourstxt').textContent = 'Час';
                }
                else if(hours%10 > 1 && hours%10 < 5){
                    document.querySelector('#hourstxt').textContent = 'Часа';
                }

                if(minutes%10 === 0 || minutes%10 > 4 || Math.floor(minutes/10) === 1){
                    document.querySelector('#minutestxt').textContent = 'Минут';
                }
                else if(minutes%10 === 1){
                    document.querySelector('#minutestxt').textContent = 'Минута';
                }
                else if(minutes%10 > 1 && minutes%10 < 5){
                    document.querySelector('#minutestxt').textContent = 'Минуты';
                }

                if(seconds%10 === 0 || seconds%10 > 4 || Math.floor(seconds/10) === 1){
                    document.querySelector('#secondstxt').textContent = 'Секунд';
                }
                else if(seconds%10 === 1){
                    document.querySelector('#secondstxt').textContent = 'Секунда';
                }
                else if(seconds%10 > 1 && seconds%10 < 5){
                    document.querySelector('#secondstxt').textContent = 'Секунды';
                }
            }
            timer();
            setInterval(timer, 1000);
        </script>

{% endblock %}

hackaton/templates/hackaton/info.html
{% extends 'hackaton/layout.html' %}
{% load static %}

    {% block main %}

    <!-- Start Breadcrumbs -->
    <div class="breadcrumbs">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-8 offset-lg-2 col-md-12 col-12">
                    <div class="breadcrumbs-content">
                        <h1 class="page-title">Информация</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Breadcrumbs -->

<!-- Start Features Area -->
     <section class="features section">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="section-title">
                        <h2 class="wow fadeInUp" data-wow-delay=".4s">Состав оргкомитета</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".2s">
                    <!-- Start Single Feature -->
                    <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
                        <span class="serial">01</span>
                        <div class="">
                            <img src="{% static 'hackaton/images/lazarevaim.jpg' %}" alt="#" width="120px" height="120px" >
                        </div>
                        <h3>Лазарева Ирина Михайловна</h3>
                        <p>кандидат физико-математических наук,
                            доцент, зав. кафедрой математики, физики и ИТ МАГУ — председатель
                            оргкомитета
                            </p>
                    </div>
                    <!-- End Single Feature -->
                </div>
                <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".4s">
                    <!-- Start Single Feature -->
                    <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
                        <span class="serial">02</span>
                        <div class="">
                            <img src="{% static 'hackaton/images/lyash_oi.jpg' %}" alt="#"  >
                        </div>
                        <h3>Ляш Олег Иванович</h3>
                        <p>кандидат педагогических наук, доцент, доцент
                            кафедры математики, физики и ИТ МАГУ — зам. председателя оргкомитета
                            </p>
                    </div>
                    <!-- End Single Feature -->
                </div>
                <div class="col-lg-4 col-md-6 col-12 wow fadeInUp" data-wow-delay=".6s">
                    <!-- Start Single Feature -->
                    <div class="single-featuer">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
                        <span class="serial">03</span>
                        <div class="">
                            <img src="{% static 'hackaton/images/lyash_aa.jpg' %}" alt="#" width="120px" height="120px">
                        </div>
                        <h3>Ляш Ася Анатольевна </h3>
                        <p>кандидат педагогических наук, доцент кафедры
                            математики, физики и ИТ МАГУ — руководитель рабочей группы

                            </p>
                    </div>
                    <!-- End Single Feature -->
                </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /End Features Area -->

     <div class="main-content text-dark">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 wow fadeInUp" data-wow-delay=".2s">

                    <div class="single-featuer text-center">
                    <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                    <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                        <h3>МЕСТО ПРОВЕДЕНИЯ</h3>
                        <p>
                            Мурманский арктический государственный университет:<br>
                            Молодежный центр технологического и социального предпринимательства
                            «Коворкинг-51»<br>
                            ул. Капитана Егорова, д. 15, МАГУ (главный корпус), вход со двора
                        </p>
                    </div> <br>


                        <div class="text-center">
                            <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A05315f509374d72b37aaa0ca3ac1ec870b939ac48ecc3e9ffbb20f4128f1ecf7&amp;source=constructor" width="100%" height="400" frameborder="0"></iframe>
                        </div>

                    <div class="row">
                    <div class="col-lg-4 col-md-6 col-12">
                        <div class="single-featuer">
                        <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                        <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                        <h3>КАК К НАМ ПРОЕХАТЬ</h3>
                        <p>
                            Проезд на площадку проведения соревнования возможен:<br>
                            ✔ троллейбусами No 3, 6;<br>
                            ✔ автобусом No 18;<br>
                            ✔ маршрутным такси No 51<br>
                            до остановки «Улица Капитана Егорова».
                        </p>
                    </div>
                    </div>
                        <div class="col-lg-4 col-md-6 col-12">
                        <div class="single-featuer">
                        <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                        <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">

                        <h3>ЧТО БУДЕТ ДОСТУПНО</h3>
                        <p>
                            На площадке для участников будут доступны:<br>
                            ✔ горячая вода <br>
                            ✔ чай<br>
                            ✔ одноразовая посуда <br>
                            ✔ мелкие «вкусняшки» (например, печенье) <br>

                        </p>
                    </div>
                </div>

                <div class="col-lg-4 col-md-6 col-12">
                    <div class="single-featuer">
                        <img class="shape" src="{% static 'hackaton/images/features/shape.svg' %}" alt="#">
                        <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
                        <h3>РЕКОМЕНДУЕТСЯ ИМЕТЬ С СОБОЙ</h3>
                        <p>
                            С собой рекомендуется брать:<br>
                            ✔сменную обувь (или бахилы)<br>
                            ✔ обычную питьевую воду (бутилированную) <br>
                            ✔ всё остальное, что не противоречит Положению о соревновании <br>
                        </p>
                    </div>

                </div></div>
                </div>

            </div>
        </div>
    </div>



    {% endblock %}

hackaton/templates/hackaton/layout.html
{% load static %}
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>NordHack-2019</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'hackaton/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'hackaton/css/headers.css' %}" rel="stylesheet">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'hackaton/css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'hackaton/css/LineIcons.3.0.css' %}" />
    <link rel="stylesheet" href="{% static 'hackaton/css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'hackaton/css/tiny-slider.css' %}" />
    <link rel="stylesheet" href="{% static 'hackaton/css/glightbox.min.css' %}" />
    {% if request.resolver_match.app_name == 'users' or request.resolver_match.url_name == 'polozhenie_nordhack' or request.resolver_match.url_name == 'day1' or request.resolver_match.url_name == 'day2' or request.resolver_match.url_name == 'day3' %}
        <link rel="stylesheet" href="{% static 'hackaton/css/main1.css' %}" />
    {% else %}
        <link rel="stylesheet" href="{% static 'hackaton/css/main.css' %}" />
    {% endif %}
</head>
<!-- Start Header Area -->
<header class="header navbar-area">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <div class="nav-inner">
                    <!-- Start Navbar -->
                    <nav class="navbar navbar-expand-lg">
                        <a class="navbar-brand" href="https://www.masu.edu.ru/">
                            <img src="{% static 'hackaton/images/logo/logo.svg'%}" alt="Logo">
                        </a>
                        <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse"
                                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                            <span class="toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                            <ul id="nav" class="navbar-nav ms-auto">
                                <li class="nav-item">
                                    <a href="{% url 'hackaton:index' %}"
                                       {% if request.resolver_match.url_name == 'index' %}
                                        class="active"
                                       {% endif %}
                                       aria-label="Toggle navigation">Главная страница</a>
                                </li>
                                {% if not request.user.is_authenticated %}
                                <li class="nav-item">
                                       <a href="{% url 'users:registration' %}"
                                        {% if request.resolver_match.url_name == 'registration' %}
                                            class="active"
                                        {% endif %} aria-label="Toggle navigation">Регистрация</a>
                                </li>
                                {% endif %}
                                <li class="nav-item">
                                    <a href="{% url 'hackaton:partners' %}"
                                       {% if request.resolver_match.url_name == 'partners' %}
                                        class="active"
                                       {% endif %}
                                    aria-label="Toggle navigation">Партнеры</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'hackaton:info' %}"
                                       {% if request.resolver_match.url_name == 'info' %}
                                        class="active"
                                       {% endif %}aria-label="Toggle navigation">Информация</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'users:profile' %}"
                                       {% if request.resolver_match.url_name == 'profile' %}
                                        class="active"
                                       {% endif %}
                                       aria-label="Toggle navigation">Личный кабинет</a>
                                </li>
                            </ul>

                        </div> <!-- navbar collapse -->
                        {% if request.resolver_match.url_name != 'registration' and not request.user.is_authenticated %}
                        <div class="button">
                            <a href="{% url 'users:registration' %}" class="btn">Зарегистрироваться<i class="lni lni-ticket"></i></a>
                        </div>
                        {% endif %}
                    </nav>
                    <!-- End Navbar -->
                </div>
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</header>
<!-- End Header Area -->

    {% block main %}
    {% endblock %}
<!-- Start Footer -->
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'hackaton:index' %}" class="nav-link px-4 text-muted">Главная страница</a></li>
            <li class="nav-item"><a href="{% url 'users:registration' %}" class="nav-link px-4 text-muted">Регистрация</a></li>
            <li class="nav-item"><a href="{% url 'hackaton:partners' %}" class="nav-link px-4 text-muted">Партнеры</a></li>
            <li class="nav-item"><a href="{% url 'hackaton:info' %}" class="nav-link px-4 text-muted">Информация</a></li>
            <li class="nav-item"><a href="{% url 'users:profile' %}" class="nav-link px-4 text-muted">Личный кабинет</a></li>
            <li class="nav-item"><a href="{% url 'hackaton:polozhenie_nordhack' %}" class="nav-link px-4 text-muted">Положение о соревновании</a></li>
        </ul>
        <p class="text-center text-muted">2023 Мурманский Арктический государственный университет</p>
    </footer>
</div>
<!-- End Footer -->


        <script src="{% static 'hackaton/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'hackaton/js/wow.min.js' %}"></script>
        <script src="{% static 'hackaton/js/tiny-slider.js' %}"></script>
        <script src="{% static 'hackaton/js/glightbox.min.js' %}"></script>
        <script src="{% static 'hackaton/js/count-up.min.js' %}"></script>
        <script src="{% static 'hackaton/js/main.js' %}"></script>
        <script src="{% static 'hackaton/js/bootstrap.bundle.min.js' %}"></script>
        </body>

</html>

hackaton/templates/hackaton/polozhenie.html
{% extends 'hackaton/layout.html' %}
{% load static %}

    {% block main %}
   <!-- Start Breadcrumbs -->

   <div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8 offset-lg-2 col-md-12 col-12">
                <div class="breadcrumbs-content">
                    <!--<h1 class="page-title">Личный кабинет</h1>-->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumbs -->
          <div class="main-doc">
              <embed src="{% static file %}" width="100%" height="100%" />
          </div>
{% endblock %}