hackatonSite/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('nordhack/', include('hackaton.urls')),
    path('nordhack/users/', include('users.urls')),
    path('nordhack/admin/', admin.site.urls),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("", views.profile, name='profile'),
    path("login", views.login_view, name='login'),
    path("logout", views.logout_view, name='logout'),
    path("addCommand", views.add_command, name='add_command'),
    path("delCommand", views.del_command, name='del_command'),
    path("addMember", views.add_member, name='add_member'),
    path("delMember", views.del_member, name='del_member'),
    path("register", views.register, name='registration'),
    path("update_user_info", views.update_user_info, name='update_user_info'),
    path("deleteUser", views.delete_user, name='delete_user'),
    path("command", views.command, name='command'),
    path("schedule", views.schedule, name='schedule'),
    path("task", views.task, name='task'),
    path("newTask", views.new_task, name='new_task'),
    path("changeTask", views.change_task, name='change_task'),
    path("newHackathon", views.new_hackathon, name='new_hackathon'),
    path("updateDateHackathon", views.update_date_hackathon, name='update_date_hackathon'),
    path("add_representative", views.add_representative, name='add_representative'),
    path("add_org", views.add_org, name='add_org'),
    path("add_task", views.add_task, name='add_task'),
]

users/forms.py
from django import forms
from django.contrib.auth.models import AbstractUser

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegForm(forms.Form):
    username = forms.CharField()
    mail = forms.EmailField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)

class UserInfoForm(forms.Form):
    first_name = forms.CharField()
    middle_name = forms.CharField()
    last_name = forms.CharField()
    mail = forms.CharField()
    job = forms.CharField()
    birth_date = forms.DateField()

class TeamForm(forms.Form):
    team = forms.CharField()
    name = forms.CharField()
class TeamMemberForm(forms.Form):
    name = forms.CharField()

class HackathonForm(forms.Form):
    name = forms.CharField()
    start_date = forms.DateField()
    end_date = forms.DateField()
    description = forms.CharField()

class HackathonDateForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

class AddRepresentativeForm(forms.Form):
    name = forms.CharField()

class OrgForm(forms.Form):
    org_name = forms.CharField()
    description = forms.CharField()
    email = forms.CharField()
    link_to_logo = forms.CharField()
    link_to_organization_website = forms.CharField()
    what_can_provide = forms.CharField()

class TaskForm(forms.Form):
    purpose = forms.CharField()
    description = forms.CharField()
    input_data = forms.CharField()

MemberFormset = forms.formset_factory(TeamMemberForm, extra=1)

users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.forms import formset_factory
from django.http import FileResponse
from .forms import LoginForm, RegForm, UserInfoForm, TeamForm, TeamMemberForm, MemberFormset, HackathonForm, HackathonDateForm, AddRepresentativeForm, OrgForm, TaskForm
from .models import Teams, MemberTeam, Profile, Tasks, HackathonsRegulations, Hackathons, Moderators, RepresentativesOrganizations, ParticipatingOrganizations


# Create your views here.
def profile(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    elif request.user.is_superuser:
        return render(request, "users/admin.html")
    elif RepresentativesOrganizations.objects.filter(user=request.user):
        return render(request, "users/representative_org.html")
    else:
        return render(request, "users/personal.html")

def login_view(request):
    if request.method == 'POST':

        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user is not None:
                login(request, user)
                return  HttpResponseRedirect(reverse('users:profile'))
            else:
                return render(request, 'users/login.html', {
                    'message':'Неправильное имя пользователя или пароль',
                })

    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'Вы вышли из системы',
    })

def add_command(request):
    if request.user.is_authenticated:
        teams = Teams.objects.all()
        member_form = MemberFormset()
        return render(request, "users/add_command.html", {
            'teams': teams,
            'formset':member_form
        })
    return render(request, "users/login.html")
def del_command(request):
    if request.user.is_authenticated:
        team = Teams.objects.filter(name=request.user.memberteam.team)
        team.delete()
        return HttpResponseRedirect(reverse("users:command"))
    return render(request, "users/login.html")
def add_member(request):
    if request.user.is_authenticated:
        member_form = TeamMemberForm(request.POST)
        members = member_form.data.getlist('name')
        users = User.objects.filter(username__in=members)
        for user in users:
            team_member = MemberTeam(team=request.user.memberteam.team, user=user)
            team_member.save()
        return HttpResponseRedirect(reverse("users:command"))

    return render(request, "users/login.html")
def del_member(request):
    if request.user.is_authenticated:
        member_form = TeamMemberForm(request.POST)
        members = member_form.data.getlist('name')
        users = User.objects.filter(username__in=members)
        for user in users:
            user.memberteam.delete()
        return HttpResponseRedirect(reverse("users:command"))

    return render(request, "users/login.html")
def command(request):
# Должна быть проверка на существование команды в БД -- ГОТОВО
# Если существует, то запрет на создание -- ГОТОВО
# Если не существует, то проверка есть ли у предлагаемых участников команда -- ГОТОВО
# Если все участники свободны, то создание команды и привязка участников к команде -- ГОТОВО
# Если участник уже в команде, то вывод страницы с инфой о команде и настройками (в html можно настроить)
# Проблема: Нужна таблица с командами, расширить модель User, обработка формы разных размеров -- ГОТОВО
    if request.user.is_authenticated:
        if MemberTeam.objects.filter(user=request.user):
            return render(request, "users/team.html", {'members':request.user.memberteam.team_members(team=request.user.memberteam.team)})
        else:

            if request.method == 'POST':
                team_form = TeamForm(request.POST)
                if team_form.is_valid():
                    team_name = team_form.cleaned_data['team']
                    members = team_form.data.getlist('name')
                    users = User.objects.filter(username__in=members)
                    if (not Teams.objects.filter(name=team_name)) \
                            and (users.count() == int(request.POST['form-TOTAL_FORMS']))\
                            and not all(MemberTeam.objects.filter(user=user) for user in users):
                        team = Teams(name=team_name,
                                     hackathon_number=Hackathons.objects.all()[0],)
                        team.save()
                        for user in users:
                            team_member = MemberTeam(team=team, user=user)
                            team_member.save()
                        team_member = MemberTeam(team=team, user=request.user)
                        team_member.save()
                        return render(request, "users/team.html",
                                      {'members': request.user.memberteam.team_members(team=request.user.memberteam.team)})

                    return render(request, "users/personal.html", {
                        'message':'Команда уже существует, либо пользователей которых вы пытаетесь добавить не существует, либо уже заняты в другой команде',
                    })

                return render(request, "users/personal.html", {

                    'message': 'форма/не/валидна',
                })

            return HttpResponseRedirect(reverse("users:profile"))

    return render(request, "users/login.html")
def register(request):

    if request.method == 'POST':

        form = RegForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            if (not User.objects.filter(username=cd['username'])) and (not User.objects.filter(email=cd['mail'])) :
                User.objects.create_user(username=cd['username'], email=cd['mail'], password=cd['password'])
                user = authenticate(username=cd['username'], password=cd['password'])

                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('users:profile'))

            else:
                return render(request, "users/registration.html", {
                    'message': 'Пользователь существует',
                })
        else:
            return render(request, "users/registration.html", {
                'message':'Неверная форма',
            })
    return render(request, "users/registration.html")


def update_user_info(request):
    if request.method == 'POST' and request.user.is_authenticated:

        form = UserInfoForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data

            # Обернуть этот блок в try/except
            user = User.objects.get(username=request.user.username)

            if not Profile.objects.filter(user=request.user):
                profile = Profile(user=request.user,
                                  middle_name=cd['middle_name'],
                                  job=cd['job'],
                                  birth_date=cd['birth_date'],)
                user.first_name = cd['first_name']
                user.last_name = cd['last_name']
                if user.email != cd['mail']:
                    user.email = cd['mail']
                profile.save()
                user.save()

            else:
                if user.first_name != cd['first_name']:
                    user.first_name = cd['first_name']

                if user.profile.middle_name != cd['middle_name']:
                    user.profile.middle_name = cd['middle_name']

                if user.last_name != cd['last_name']:
                    user.last_name = cd['last_name']

                if user.email != cd['mail']:
                    user.email = cd['mail']

                if user.profile.job != cd['job']:
                    user.profile.job = cd['job']

                if user.profile.birth_date != cd['birth_date']:
                    user.profile.birth_date = cd['birth_date']

                user.save()
                user.profile.save()

            # Сделать вывод сообщения об изменении данных
            return HttpResponseRedirect(reverse("users:profile"))
        else:
            return render(request, "users/personal.html", {

                'message': 'Неправильно заполненная форма',
            })
    else:
        return HttpResponseRedirect(reverse("users:profile"))

def delete_user(request):
    if request.user.is_authenticated:
        user = User.objects.get(username=request.user.username)
        User.delete(user)
        logout(request)
        return render(request, 'users/login.html', {
            'message': 'Вы вышли из системы',
        })
    return render(request, "users/login.html")
def schedule(request):
    if request.user.is_authenticated:
        return render(request, 'users/schedule.html',{
            'timetable':HackathonsRegulations.objects.all(),
            'hackathon_date':Hackathons.objects.all()[0],
        })
    return render(request, "users/login.html")
def task(request):
    if request.user.is_authenticated:
        if MemberTeam.objects.filter(user=request.user):
            if request.user.memberteam.team.task_id:
                return render(request, 'users/user_task.html', {
                    'task':Tasks.objects.get(id=request.user.memberteam.team.task_id.id)
                })
            else:
                return render(request, 'users/tasks.html', {
            'tasks':Tasks.objects.all()
        })

        else:
            return render(request, 'users/tasks.html', {
                'tasks': Tasks.objects.all()
            })
    return render(request, "users/login.html")

users/templates/users/add_member_widget.html
{% load static %}

<div id="add-bg" class="bg-blackout" style="width: 100%;">
        </div>
<div id="add_member_widget" class="widget">

        <div class="single-featuer">
        <img class="shape" src="{% static 'hackaton/images/features/shape.svg'%}" alt="#">
        <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
         <form id="form-container" action="{% url 'users:add_member' %}" method="post">
            {% csrf_token %}

            <div class="form-floating" id="form-nick">
              <input type="text" class="form-control" name="name" id="form-name_0" placeholder="count">
              <label for="form-name_0">nickname участника</label>
            </div>

            <div>
                <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
                <input type="hidden" name="form-TOTAL_FORMS" value="1" id="id_form-TOTAL_FORMS">
            </div>
            <button id="add-form" class="w-100 btn btn-outline-success" type="button" style="margin-bottom: 5px; margin-top: 5px">Добавить участника</button>
            <button id="del-form" class="w-100 btn btn-outline-danger" type="button" style="margin-bottom: 5px">Удалить участника</button>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
          </form>
        </div>
    </div>

<script>
         let nickForm = document.querySelectorAll("#form-nick")
        let formNum = nickForm.length-1

        let container = document.querySelectorAll("#form-container")[0]
        let addButton = document.querySelectorAll("#add-form")[0]
        let delButton = document.querySelectorAll("#del-form")[0]
        let totalForms = document.querySelectorAll("#id_form-TOTAL_FORMS")[0]



        addButton.addEventListener('click', addForm)
        delButton.addEventListener('click', delForm)

        function addForm(e){
           e.preventDefault()

            if (totalForms.getAttribute('value') < (5 - {{ members.count }})){
                let newForm = nickForm[0].cloneNode(true)
                let formRegex = RegExp(`name_(\\d){1}`,'g')

                formNum++
                newForm.innerHTML = newForm.innerHTML.replace(formRegex, `name_${formNum}`)
                container.insertBefore(newForm, addButton)
                totalForms.setAttribute('value', `${formNum+1}`)
            }
        }

        function delForm(e){+
            e.preventDefault()

            if (totalForms.getAttribute('value') > 1){
                let form = document.querySelector(`#form-name_${formNum}`)
                let form1 = document.querySelector(`#form-name_${formNum}`)
                form.parentElement.remove()
                form1.parentElement.remove()
                formNum--
                totalForms.setAttribute('value', `${formNum+1}`)
            }
        }
</script>

users/templates/users/add_org_widget.html
{% load static %}

<div id="add-bg" class="bg-blackout" style=" width: 150%; height: 250%" xmlns="http://www.w3.org/1999/html">
        </div>
<div id="add_org_widget" class="widget">

        <div class="single-featuer">
        <img class="shape" src="{% static 'hackaton/images/features/shape.svg'%}" alt="#">
        <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
         <form id="form-container" action="{% url 'users:add_org' %}" method="post">
            {% csrf_token %}

            <div class="form-floating" id="form-org_name">
              <input type="text" class="form-control" name="org_name" id="org_name" placeholder="count">
              <label for="org_name">Название организации</label>
            </div>

             <div class="form-floating" id="form-email">
              <input type="email" class="form-control" name="email" id="email" placeholder="count">
              <label for="email">email</label>
            </div>

            <div class="form-floating" id="form-description">
              <input type="text" class="form-control" name="description" id="description" placeholder="count">
              <label for="description">Описание организации</label>
            </div>

              <div class="form-floating" id="form-logo">
              <input type="text" class="form-control" name="link_to_logo" id="logo" placeholder="count">
              <label for="logo">Ссылка на лого организации</label>
            </div>

             <div class="form-floating" id="form-website">
              <input type="text" class="form-control" name="link_to_organization_website" id="website" placeholder="count">
              <label for="website">Ссылка на сайт организации</label>
            </div>

             <div class="form-floating" id="form-provide">
              <input type="text" class="form-control" name="what_can_provide" id="provide" placeholder="count">
              <label for="provide">Что может предоставить</label>
            </div>

            <button class="w-100 btn btn-lg btn-primary" type="submit">Добавить организацию</button>
          </form>
        </div>
    </div>

users/templates/users/add_representatives_widget.html
{% load static %}

<div id="add-bg" class="bg-blackout" style="width: 100%;" xmlns="http://www.w3.org/1999/html">
        </div>
<div id="add_representative_widget" class="widget">

        <div class="single-featuer">
        <img class="shape" src="{% static 'hackaton/images/features/shape.svg'%}" alt="#">
        <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
         <form id="form-container" action="{% url 'users:add_representative' %}" method="post">
            {% csrf_token %}

            <div class="form-floating" id="form-nick">
              <input type="text" class="form-control" name="name" id="name" placeholder="count">
              <label for="name">nickname пользователя</label>
            </div>

            <button class="w-100 btn btn-lg btn-primary" type="submit">Добавить представителя</button>
          </form>
        </div>
    </div>

users/templates/users/add_task_widget.html
{% load static %}

<div id="add-bg" class="bg-blackout" style=" width: 150%; height: 250%" xmlns="http://www.w3.org/1999/html">
        </div>
<div id="add_task_widget" class="widget">

        <div class="single-featuer">
        <img class="shape" src="{% static 'hackaton/images/features/shape.svg'%}" alt="#">
        <img class="shape2" src="{% static 'hackaton/images/features/shape2.svg' %}" alt="#">
         <form id="form-container" action="{% url 'users:add_task' %}" method="post">
            {% csrf_token %}

            <div class="form-floating" id="form-purpose">
              <input type="text" class="form-control" name="purpose" id="purpose" placeholder="count">
              <label for="purpose">Цель</label>
            </div>

            <div class="form-floating" id="form-description">
              <input type="text" class="form-control" name="description" id="description" placeholder="count">
              <label for="description">Описание</label>
            </div>

              <div class="form-floating" id="form-input_data">
              <input type="text" class="form-control" name="input_data" id="input_data" placeholder="count">
              <label for="input_data">Входные данные</label>
            </div>

            <button class="w-100 btn btn-lg btn-primary" type="submit">Добавить задачу</button>
          </form>
        </div>
    </div>

users/templates/users/admin.html
{% extends 'users/profile.html' %}
{% load static %}

{% block body %}

<div class="main-text">

        <div class="main-text">
                <!--Start Form-->
            <p class="lead">  {{ message }}</p>
      <div class="form-signin">
         <form action="{% url 'users:update_user_info' %}" method="post">
             {% csrf_token %}
       <div class="form-floating mb-3">
        <h4>Фамилия</h4>
         <input type="text" value="{{ user.last_name }}" name="last_name" class="form-control" id="floatingInput">
       </div>
       <div class="form-floating mb-3">
        <h4>Имя</h4>
         <input type="text" value="{{ user.first_name }}" name="first_name" class="form-control" id="floatingInput" >
       </div>

       <div class="form-floating mb-3">
        <h4>Отчество</h4>
         <input type="text" value="{{ user.profile.middle_name }}" name="middle_name" class="form-control" id="floatingInput" >
       </div>
       <div class="form-floating mb-3">
       <h4>Дата рождения</h4>
          <input type="date" value="{{ user.profile.birth_date|date:'Y-m-d' }}" name="birth_date" class="form-control" id="floatingInput">
        </div>
       <div class="form-floating mb-3">
        <h4>Учебное заведение/Место работы</h4>
         <input type="text" value="{{ user.profile.job }}" name="job" class="form-control" id="floatingInput">
       </div>
       <div class="form-floating mb-3">
        <h4>Электронная почта</h4>
          <input type="email" value="{{ user.email }}" name="mail" class="form-control" id="floatingInput" placeholder="name@example.com">
        </div>
       <div class="text-center">
           <div>
         <button id="add_hackaton" class="w-150 btn btn-lg btn-primary" type="button">Создать хакатон</button>
          <button id="add_representative" class="w-150 btn btn-lg btn-primary" type="button">Добавить представителя</button>
       <button id="update_date_hackathon" class="w-150 btn btn-lg btn-primary" type="button">Обновить дату Хакатона</button>
        <a href="{% url 'admin:index' %}" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Работа с БД</a>
           </div>
       <p class="lead">
           <button class="w-150 btn btn-lg btn-primary" type="submit">Сохранить изменения</button>
          <a href="{% url 'users:delete_user' %}" class="btn btn-lg btn-secondary fw-bold border-danger bg-danger text-white">Удалить себя</a>
         <a href="{% url 'users:logout' %}" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Выйти</a>

       </p>
           </div>
     </form>
</div>

          {% include 'users/add_hackaton_widget.html' %}
          {% include 'users/add_representatives_widget.html' %}
            {% include 'users/update_hackathon_date_widget.html' %}

</div>
</div>

   <script>
        var bg = document.querySelector('.bg-blackout')
        var add_hackaton_widget = document.querySelector('#add_hackaton_widget');
        var add_representative_widget = document.querySelector('#add_representative_widget');
        var update_date_hackathon_widget = document.querySelector('#update_date_hackathon_widget');
        var add_hackaton = document.querySelector('#add_hackaton');
        var add_representative = document.querySelector('#add_representative');
        var update_date_hackathon = document.querySelector('#update_date_hackathon');

       add_hackaton.addEventListener('click', function() {
          bg.style.display = 'block';
          add_hackaton_widget.style.display = 'block';
        });

        add_representative.addEventListener('click', function() {
          bg.style.display = 'block';
          add_representative_widget.style.display = 'block';
        });
        update_date_hackathon.addEventListener('click', function() {
          bg.style.display = 'block';
          update_date_hackathon_widget.style.display = 'block';
        });
        bg.addEventListener('click', function() {
          bg.style.display = 'none';
          addwidget.style.display = 'none';
          delwidget.style.display = 'none';
        });




   </script>
{% endblock %}

users/templates/users/personal.html
{% extends 'users/profile.html' %}
{% load static %}

    {% block body %}
  <div class="main-text">
    <!--Start Form-->
      <p class="lead">  {{ message }}</p>
      <div class="form-signin">
         <form action="{% url 'users:update_user_info' %}" method="post">
             {% csrf_token %}
       <div class="form-floating mb-3">
        <h4>Фамилия</h4>
         <input type="text" value="{{ user.last_name }}" name="last_name" class="form-control" id="floatingInput">
       </div>
       <div class="form-floating mb-3">
        <h4>Имя</h4>
         <input type="text" value="{{ user.first_name }}" name="first_name" class="form-control" id="floatingInput" >
       </div>

       <div class="form-floating mb-3">
        <h4>Отчество</h4>
         <input type="text" value="{{ user.profile.middle_name }}" name="middle_name" class="form-control" id="floatingInput" >
       </div>
       <div class="form-floating mb-3">
       <h4>Дата рождения</h4>
          <input type="date" value="{{ user.profile.birth_date|date:'Y-m-d' }}" name="birth_date" class="form-control" id="floatingInput">
        </div>
       <div class="form-floating mb-3">
        <h4>Учебное заведение/Место работы</h4>
         <input type="text" value="{{ user.profile.job }}" name="job" class="form-control" id="floatingInput">
       </div>
       <div class="form-floating mb-3">
        <h4>Электронная почта</h4>
          <input type="email" value="{{ user.email }}" name="mail" class="form-control" id="floatingInput" placeholder="name@example.com">
        </div>
       <div class="text-center">
       <p class="lead">
           <button class="w-150 btn btn-lg btn-primary" type="submit">Сохранить изменения</button>
          <a href="{% url 'users:delete_user' %}" class="btn btn-lg btn-secondary fw-bold border-danger bg-danger text-white">Удалить себя</a>
         <a href="{% url 'users:logout' %}" class="btn btn-lg btn-secondary fw-bold border-white bg-white">Выйти</a>

       </p>
           </div>
     </form>


</div>


        </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'hackaton/layout.html' %}
{% load static %}

    {% block main %}

   <!-- Start Breadcrumbs -->

   <div class="breadcrumbs">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-8 offset-lg-2 col-md-12 col-12">
                <div class="breadcrumbs-content">
                    <!--<h1 class="page-title">Личный кабинет</h1>-->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Breadcrumbs -->

<div class="wrapper">
  <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="{% url 'users:profile' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
      <span class="fs-4">Личный кабинет</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="{% url 'users:profile' %}"
            {% if request.resolver_match.url_name == 'profile' %}
                class="nav-link active" aria-current="page"
            {% else %}
                class="nav-link text-white"
            {% endif %} >
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
          Обо мне
        </a>
      </li>
      <li>
        <a {% if user.memberteam == '' %}
                href="{% url 'users:add_command' %}"
           {% else %}
                href="{% url 'users:command' %}"
           {% endif %}
           {% if request.resolver_match.url_name == 'add_command' or request.resolver_match.url_name == 'command' %}
                class="nav-link active" aria-current="page"
            {% else %}
                class="nav-link text-white"
            {% endif %} >
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"/></svg>
          Команда
        </a>
      </li>
      <li>
        <a href="{% url 'users:schedule' %}"
            {% if request.resolver_match.url_name == 'schedule' %}
                class="nav-link active" aria-current="page"
            {% else %}
                class="nav-link text-white"
            {% endif %} >
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
          Расписание
        </a>
      </li>
      <li>
        <a href="{% url 'users:task' %}"
            {% if request.resolver_match.url_name == 'task' %}
                class="nav-link active" aria-current="page"
            {% else %}
                class="nav-link text-white"
            {% endif %} >
          <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"/></svg>
          Задача
        </a>
      </li>
        </ul>
    <hr>
   </div>


    {% block body %}
    {% endblock %}
</div>
    {% endblock %}

users/templates/users/registration.html
{% extends 'hackaton/layout.html' %}
{% load static %}
{% block main %}
   <!-- Start Breadcrumbs -->
   <div class="breadcrumbs">
       <div class="container">
           <div class="row align-items-center">
               <div class="col-lg-8 offset-lg-2 col-md-12 col-12">
                   <div class="breadcrumbs-content">

                   </div>
               </div>
           </div>
       </div>
   </div>
   <!-- End Breadcrumbs -->
<div class="text-center"><h1 class="page-title">Регистрация</h1></div>
   <!--Start Form-->
   <div class="main-content text-dark">
   <main class="form-signin">
    <div class="container">
        <form action="{% url 'users:registration' %}" method="post">
        {% csrf_token %}
      <p>{{ message }}</p>
        <div class="form-floating">
          <input type="text" name="username" class="form-control" id="floatingName" placeholder="name">
          <label for="floatingName">Имя пользователя</label>
        </div>
      <div class="form-floating">
        <input type="email" name="mail" class="form-control" id="floatingInput" placeholder="name@example.com">
        <label for="floatingInput">Адрес электронной почты</label>
      </div>
      <div class="form-floating">
        <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Пароль</label>
      </div>

      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Запомнить меня
        </label>
      </div>
      <div class="text-center">
      <button class="w-150 btn btn-lg btn-primary" type="submit">Зарегистрироваться</button></div>
    </form>
  </div>
  </main> </div>
  <!--End Form-->
{% endblock %}